# Generated by Django 4.1.7 on 2024-01-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flipnote',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('real_filename', models.CharField(max_length=24)),
            ],
        ),
    ]
