# Generated by Django 4.1.7 on 2024-01-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flipnote',
            name='saved',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flipnote',
            name='views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flipnote',
            name='real_filename',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
