# Generated by Django 4.1.7 on 2024-01-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_session_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban',
            field=models.BooleanField(default=False),
        ),
    ]
