# Generated by Django 4.1.7 on 2024-01-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_rename_session_id_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='temp',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='session',
            name='token',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
