# Generated by Django 4.1.7 on 2024-01-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_session_fsid_session_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fsid',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mac',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
