# Generated by Django 4.1.7 on 2024-01-14 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_alter_user_fsid_alter_user_mac'),
    ]

    operations = [
        migrations.AddField(
            model_name='flipnote',
            name='made_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='fsid',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mac',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
