# Generated by Django 4.1.7 on 2024-01-14 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_channel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='flipnote',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.channel'),
            preserve_default=False,
        ),
    ]
