# Generated by Django 4.1.7 on 2024-01-15 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_flipnote_blue_star_flipnote_green_star_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarLog',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('star', models.IntegerField(default=0)),
                ('green_star', models.IntegerField(default=0)),
                ('red_star', models.IntegerField(default=0)),
                ('blue_star', models.IntegerField(default=0)),
                ('purple_star', models.IntegerField(default=0)),
                ('flipnote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.flipnote')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
