# Generated by Django 4.1.7 on 2024-01-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_starlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='flipnote',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
