# Generated by Django 4.1.7 on 2024-01-15 04:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_flipnote_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='flipnote',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
