# Generated by Django 4.1.7 on 2024-01-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_flipnote_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel',
            name='show_in_frontpage',
            field=models.BooleanField(default=True),
        ),
    ]
